# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: HDR UK Phenotype Library
email: feedback@phenotype.id
description: >- # this means to ignore newlines until "baseurl:"
  HDR UK Phenotype Library
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://phenotype.id" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: HDR_UK
github_username:  hdruk
google_analytics: UA-32217823-3

# Build settings
theme: minima

whitelist:
  - jekyll-redirect-from

plugins:
  - jekyll-feed
  - jekyll-redirect-from

collections:
  # TODO: Add death, primary_care and secondary_care as data collections
  phenotypes:
    sort_by: phenotype_id
    output: true
    permalink: /phenotypes/:name

algolia:
  application_id: 'O61CFTQFTF'
  index_name: phenotypes
  search_only_api_key: dc264b8886b8a8beeaa1eff99f530d48
  settings:                                                                      
    searchableAttributes:                                                        
      - title                                                                    
      - phenotype_id                                                             
      - content                                                                  
      - collection,categories,tags                                               
      - type                                                                     
      - group                                                                    
      - clinical_terminologies 
  files_to_exclude:
    - index.md
    - README.md
    - phenotypes.md
    - primary_care/*
    - secondary_care/*
    - assets/*

  

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
